#!/usr/bin/env python3
"""
Hybrid Cascade Investigation - Runner Script
Automates the multi-agent workflow for comprehensive research.
"""

import os
import sys
import json
import subprocess
from datetime import datetime
from pathlib import Path

def sanitize_filename(name):
    """Convert topic to safe filename."""
    return "".join(c if c.isalnum() or c in (' ', '-', '_') else '_' for c in name).replace(' ', '-').lower()

def create_output_dir(topic, base_dir="~/Desktop/qibin/investigations"):
    """Create timestamped output directory."""
    base = Path(base_dir).expanduser()
    date_str = datetime.now().strftime("%Y-%m-%d")
    topic_slug = sanitize_filename(topic)
    output_dir = base / f"{date_str}_{topic_slug}"
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir

def generate_frontmatter(topic, metadata):
    """Generate Obsidian frontmatter."""
    now = datetime.now()
    return f"""---
title: "{topic}"
date: {now.strftime("%Y-%m-%d %H:%M")}
date_created: {now.isoformat()}
investigation_type: hybrid_cascade
agents_phase1: {metadata.get('phase1_agents', 2)}
agents_phase2: {metadata.get('phase2_agents', 0)}
total_agents: {metadata.get('total_agents', 2)}
total_duration_minutes: {metadata.get('total_duration', 0)}
phase1_duration: {metadata.get('phase1_duration', 0)}
phase2_duration: {metadata.get('phase2_duration', 0)}
confidence_level: {metadata.get('confidence', 'medium')}
citations_count: {metadata.get('citations_total', 0)}
citations_verified: {metadata.get('citations_verified', 0)}
topics_identified: {metadata.get('topics_found', 0)}
gaps_found: {metadata.get('gaps_found', 0)}
gaps_investigated: {metadata.get('gaps_investigated', 0)}
tags:
  - research
  - investigation
  - hybrid_cascade
aliases:
  - "{topic[:30]}"
---

"""

def create_readme(output_dir, topic):
    """Create orientation README."""
    readme = output_dir / "README.md"
    readme.write_text(f"""# Investigation: {topic}

## Quick Orientation

This directory contains a **hybrid cascade investigation** with the following structure:

| File | Purpose |
|------|---------|
| `*.md` (main file) | Synthesized findings in Obsidian format |
| `raw_findings_phase1.json` | Complete outputs from Phase 1 agents |
| `raw_findings_phase2.json` | Complete outputs from Phase 2 agents |
| `citation_log.csv` | All sources with verification status |
| `gap_analysis.md` | Mapping of Phase 1 findings → Phase 2 deep dives |

## Workflow Summary

1. **Phase 1**: Quick redundancy scan (2 agents, 4-5 searches each)
2. **Gap Analysis**: Identify consensus vs gaps
3. **Phase 2**: Targeted deep dives (1 agent per gap)
4. **Synthesis**: Combined output with verified citations

## Confidence Levels

- ✅ **High**: Confirmed by 2+ agents
- ⚠️ **Medium**: Found by 1 agent, cross-referenced
- 🔍 **Low**: Single source, needs verification

---
*Generated by hybrid-cascade-investigation skill*
""")

if __name__ == "__main__":
    print("Hybrid Cascade Investigation Runner")
    print("Use via Hermes skill system, not directly.")
    print(f"Default output: ~/Desktop/qibin/investigations/")
